### ISSUE TITLE
Deployment on Kubernetes cluster behhind ingress

### ISSUE THREAD

**Issue by KhalilAwada** [cloudamqp/websocket-tcp-relay#20]
I'm having trouble configuring cloudamqp/websocket-tcp-relay behind ingress in a Kubernetes cluster

ingress annotations are as following:
```
annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_http_version 1.1;
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
    nginx.org/websocket-services: websocket-tcp-relay
    nginx.ingress.kubernetes.io/protocol: "WebSocket"
    nginx.ingress.kubernetes.io/upgrade-websocket: "true"
```
    
```
spec:
  tls:
    - hosts:
        - <domain>
      secretName: websocket-tcp-relay-tls
  rules:
    - host: <domain>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websocket-tcp-relay
                port:
                  number: 15670
```

Are there any instructions on how to implement this setup ?
